version: '3.9'

services:

  db:
    image: postgis/postgis:14-3.3
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: ecommerce_backend
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "9000:9000"
    command: ./entrypoint.sh

  frontend:
    build:
      context: ./frontend
    container_name: ecommerce_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
